### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by borondics** [mcs07/ChemSpiPy#11]
Hi,

I am running this code and then getting this message, but can't do much with it:

```
In [1]: from chemspipy import ChemSpider
In [2]: cs = ChemSpider('<KEY>')
In [3]: c1 = cs.get_compound(236)
In [4]: c1.inchi
```

> ChemSpiPyAuthError: Unauthorized web service usage. Please request access to this service.

Do you have any suggestions?

Thanks!

**Comment by fredrikw** [comment]
If you look at the thread for #12 you can see that the development master uses the new API and you will also find instructions on how to install it. 
I really don’t recommend starting a new project with the old API.
