### ISSUE TITLE
Access to physical properties

### ISSUE THREAD

**Issue by alexbw** [mcs07/ChemSpiPy#17]
Hello, excellent tool, and congrats on the migration to the new REST API!
I was unable to find a way to grab any of the information from the "Properties" tab of ChemSpider. I'm specifically looking for the predicted properties from ACD/Labs, which seem to be structured and have relatively good coverage across the database. Is this something that I'd have to write my own REST requests for, or is there a feature I'm overlooking in ChemSpider?

**Comment by mcs07** [comment]
Unfortunately I don't believe this is possible with the current REST API. It may be the case that the licensing agreement between ACD/Labs and ChemSpider doesn't allow the properties to be made accessible by an API. The ChemSpider team may be able to provide more information: http://www.chemspider.com/Contact.aspx
