### ISSUE TITLE
access "data source" information through `ChemSpider`

### ISSUE THREAD

**Issue by danodonovan** [mcs07/ChemSpiPy#3]
The chemspider web ui has interesting "data source" information - like this example for [blebbistatin](http://www.chemspider.com/Chemical-Structure.2718128.html) (under "More" -> "Data Sources"). 

Is it possible to access this information through the `ChemSpider` API? For example, can we pull out the ChEMBL ID value for this compound?

PS Great tool by the way, I'm really enjoying working with it.

**Comment by danodonovan** [comment]
I imagine this would require use of the `CSID2ExtRefs` [API](http://www.chemspider.com/Search.asmx?op=CSID2ExtRefs)

**Comment by mcs07** [comment]
In the next release, this will be possible using the `get_external_references` api method, or the `external_references` property on the `Compound` object.
